src/Entity/Biens.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BiensRepository")
 */
class Biens
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $pieces;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $chambre;

    /**
     * @ORM\Column(type="integer")
     */
    private $surface;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $prix;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $charge;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $images;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $date_construction;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $etage;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $cuisine;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $bain;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $energie;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPieces(): ?int
    {
        return $this->pieces;
    }

    public function setPieces(int $pieces): self
    {
        $this->pieces = $pieces;

        return $this;
    }

    public function getChambre(): ?int
    {
        return $this->chambre;
    }

    public function setChambre(int $chambre): self
    {
        $this->chambre = $chambre;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(?int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getCharge(): ?int
    {
        return $this->charge;
    }

    public function setCharge(?int $charge): self
    {
        $this->charge = $charge;

        return $this;
    }

    public function getImages(): ?string
    {
        return $this->images;
    }

    public function setImages(?string $images): self
    {
        $this->images = $images;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateConstruction(): ?int
    {
        return $this->date_construction;
    }

    public function setDateConstruction(?int $date_construction): self
    {
        $this->date_construction = $date_construction;

        return $this;
    }

    public function getEtage(): ?int
    {
        return $this->etage;
    }

    public function setEtage(?int $etage): self
    {
        $this->etage = $etage;

        return $this;
    }

    public function getCuisine(): ?bool
    {
        return $this->cuisine;
    }

    public function setCuisine(?bool $cuisine): self
    {
        $this->cuisine = $cuisine;

        return $this;
    }

    public function getBain(): ?bool
    {
        return $this->bain;
    }

    public function setBain(?bool $bain): self
    {
        $this->bain = $bain;

        return $this;
    }

    public function getEnergie(): ?string
    {
        return $this->energie;
    }

    public function setEnergie(string $energie): self
    {
        $this->energie = $energie;

        return $this;
    }
}

src/Form/BiensType.php
<?php

namespace App\Form;

use App\Entity\Biens;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BiensType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('pieces')
            ->add('chambre')
            ->add('surface')
            ->add('adresse')
            ->add('prix')
            ->add('charge')
            ->add('images')
            ->add('description')
            ->add('date_construction')
            ->add('etage')
            ->add('cuisine')
            ->add('bain')
            ->add('energie')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Biens::class,
        ]);
    }
}

src/Controller/BiensController.php
<?php

namespace App\Controller;

use App\Entity\Biens;
use App\Form\BiensType;
use App\Repository\BiensRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/biens")
 */
class BiensController extends AbstractController
{
    /**
     * @Route("/", name="biens_index", methods={"GET"})
     */
    public function index(BiensRepository $biensRepository): Response
    {
        return $this->render('biens/index.html.twig', [
            'biens' => $biensRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="biens_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $bien = new Biens();
        $form = $this->createForm(BiensType::class, $bien);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($bien);
            $entityManager->flush();

            return $this->redirectToRoute('biens_index');
        }

        return $this->render('biens/new.html.twig', [
            'bien' => $bien,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="biens_show", methods={"GET"})
     */
    public function show(Biens $bien): Response
    {
        return $this->render('biens/show.html.twig', [
            'bien' => $bien,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="biens_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Biens $bien): Response
    {
        $form = $this->createForm(BiensType::class, $bien);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('biens_index');
        }

        return $this->render('biens/edit.html.twig', [
            'bien' => $bien,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="biens_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Biens $bien): Response
    {
        if ($this->isCsrfTokenValid('delete'.$bien->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($bien);
            $entityManager->flush();
        }

        return $this->redirectToRoute('biens_index');
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index()
    {
        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/biens/_delete_form.html.twig
<form method="post" action="{{ path('biens_delete', {'id': bien.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ bien.id) }}">
    <button class="btn">Delete</button>
</form>

templates/biens/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/biens/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Biens{% endblock %}

{% block body %}
    <h1>Edit Biens</h1>

    {{ include('biens/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('biens_index') }}">back to list</a>

    {{ include('biens/_delete_form.html.twig') }}
{% endblock %}

templates/biens/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Biens index{% endblock %}

{% block body %}
    <h1>Biens index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Pieces</th>
                <th>Chambre</th>
                <th>Surface</th>
                <th>Adresse</th>
                <th>Prix</th>
                <th>Charge</th>
                <th>Images</th>
                <th>Description</th>
                <th>Date_construction</th>
                <th>Etage</th>
                <th>Cuisine</th>
                <th>Bain</th>
                <th>Energie</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for bien in biens %}
            <tr>
                <td>{{ bien.id }}</td>
                <td>{{ bien.pieces }}</td>
                <td>{{ bien.chambre }}</td>
                <td>{{ bien.surface }}</td>
                <td>{{ bien.adresse }}</td>
                <td>{{ bien.prix }}</td>
                <td>{{ bien.charge }}</td>
                <td>{{ bien.images }}</td>
                <td>{{ bien.description }}</td>
                <td>{{ bien.dateConstruction }}</td>
                <td>{{ bien.etage }}</td>
                <td>{{ bien.cuisine ? 'Yes' : 'No' }}</td>
                <td>{{ bien.bain ? 'Yes' : 'No' }}</td>
                <td>{{ bien.energie }}</td>
                <td>
                    <a href="{{ path('biens_show', {'id': bien.id}) }}">show</a>
                    <a href="{{ path('biens_edit', {'id': bien.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="15">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('biens_new') }}">Create new</a>
{% endblock %}

templates/biens/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Biens{% endblock %}

{% block body %}
    <h1>Create new Biens</h1>

    {{ include('biens/_form.html.twig') }}

    <a href="{{ path('biens_index') }}">back to list</a>
{% endblock %}

templates/biens/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Biens{% endblock %}

{% block body %}
    <h1>Biens</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ bien.id }}</td>
            </tr>
            <tr>
                <th>Pieces</th>
                <td>{{ bien.pieces }}</td>
            </tr>
            <tr>
                <th>Chambre</th>
                <td>{{ bien.chambre }}</td>
            </tr>
            <tr>
                <th>Surface</th>
                <td>{{ bien.surface }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ bien.adresse }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ bien.prix }}</td>
            </tr>
            <tr>
                <th>Charge</th>
                <td>{{ bien.charge }}</td>
            </tr>
            <tr>
                <th>Images</th>
                <td>{{ bien.images }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ bien.description }}</td>
            </tr>
            <tr>
                <th>Date_construction</th>
                <td>{{ bien.dateConstruction }}</td>
            </tr>
            <tr>
                <th>Etage</th>
                <td>{{ bien.etage }}</td>
            </tr>
            <tr>
                <th>Cuisine</th>
                <td>{{ bien.cuisine ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Bain</th>
                <td>{{ bien.bain ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Energie</th>
                <td>{{ bien.energie }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('biens_index') }}">back to list</a>

    <a href="{{ path('biens_edit', {'id': bien.id}) }}">edit</a>

    {{ include('biens/_delete_form.html.twig') }}
{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HomeController!{% endblock %}

{% block body %}
ICI page d'accueil
{% endblock %}